openapi: 3.0.0
info:
  title: Ping API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Retourne pong
      responses:
        '200':
          description: pong
          content:
            text/plain:
              schema:
                type: string


