openapi: 3.0.0
info:
  title: Gestion de tache
  version: 1.0.0
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Faire les courses"
        completed:
          type: boolean
          example: false*
    TaskIdList:
      type: array
      items:
        type: integer
      example: [ 1, 2, 3 ]



paths:
  /task:
    get:
      summary: Return task list
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    delete:
      summary: Supprime plusieurs tâches par ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskIdList'

    /task/{id}:
      get:
       summary: Return task by id
       parameters:
        - name: id
          in : path
          required: true
          schema:
            type: integer
          description: id of the task
       responses:
          description: The requested task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          '404':
            description: Task not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: "Task not found"
      delete:
        summary: Delete task by id
        parameter:
          name: id
          in: path
          required: true
          schema:
            type: integer
        responses:
          '200':
          description: Delete succesfully
          content:
            application/json:
            schema:
              $ref: '#/components/schemas/Task'







